### ISSUE TITLE
Rename archived files

### ISSUE THREAD

**Issue by morninj** [BTLJ/btlj.org#4]
> One other idea: naming the files for their citation, as in 10btlj443(2005).pdf would also help

**Comment by amahani** [comment]
This has been fixed.
The layout of the file names are the following:

Full Issue: 29-berkeley-tech-l-j-FM-0377-1094.pdf
[Volume]-berkeley-tech-l-j-[FrontMatter(FM)]-[start-page]-[end-page].pdf

Frontmatter only:
29-berkeley-tech-l-j-FM-issue-AR.pdf
Relevant Parts: [FM]-issue-[issue].pdf
Issue: 1, 2, 3 (which is our symposium edition), and AR
The frontmatter pdfs had to differentiate between the different issues since we have 4 frontmatters per volume.

Article: 29-berkeley-tech-l-j-0385-0418.pdf
Relevant Parts: [start page of article]-[end page of article].pdf
